# Use OpenShift Python Builder image as base
FROM registry.access.redhat.com/ubi8/python-38

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Set the command to run the application
CMD ["python", "app.py"]

# Expose the port your application runs on
EXPOSE 8080

