# Use Red Hat Universal Base Image with Python 3.9
FROM registry.access.redhat.com/ubi8/python-39

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . /app

# Install application dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Expose the port that Flask runs on
EXPOSE 8080

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8080

# Run the Flask application
CMD ["flask", "run"]

